name: aoc2018 
version: 0.1.0.0

ghc-options:
    - -fwarn-tabs                      # Emit warnings of tabs instead of spaces in the source code
    - -fwarn-incomplete-uni-patterns   # Emit warnings for incomplete patterns in lambdas or pattern bindings
    - -fwarn-incomplete-patterns       # Warn on non-exhaustive patterns
    - -fwarn-overlapping-patterns      # Warn on pattern matching branches that overlap
    - -fwarn-incomplete-record-updates # Warn when records are not instantiated with all fields
    - -fno-warn-deprecations
    # - -fwarn-name-shadowing            # Warn on duplicate names in nested bindings
    # - -fwarn-missing-signatures        # Warn about toplevel missing type signatures
    # - -fwarn-monomorphism-restriction  # Warn when the monomorphism restriction is applied implicitly
    # - -fwarn-unused-imports            # Warn about libraries imported without being used
    - -threaded
    - -with-rtsopts=-N4

default-extensions:
    - OverloadedStrings

dependencies:
  - base
  - bytestring
  - text
  - vector
  - containers
  - data-default
  - process
  - time
  - extra
  - array
  - filepath
  - directory
  - optparse-applicative
  - aeson
  - yaml
  - split
  - random
  - mtl
  - profunctors
  - product-profunctors
  - http-client
  - attoparsec
  - megaparsec
  - parser-combinators
  - repa
  - lens

library:
  source-dirs: src/


executables:
    aoc:
        source-dirs:
            - execs
            - src
        main: aoc.hs
        other-modules:
            - Paths_aoc2018
            - Day1
            - Day2
            - Day3
        when:
           - condition: os(darwin)
             extra-libraries: iconv
